-- MySQL Script generated by MySQL Workbench
-- seg 04 out 2021 17:36:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_integrador_ii_a
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_integrador_ii_a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_integrador_ii_a` ;
USE `projeto_integrador_ii_a` ;

-- -----------------------------------------------------
-- Table `projeto_integrador_ii_a`.`tipo_pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador_ii_a`.`tipo_pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador_ii_a`.`questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador_ii_a`.`questionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador_ii_a`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador_ii_a`.`pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enunciado` VARCHAR(255) NOT NULL,
  `id_questionario` INT NOT NULL,
  `id_tipo_pergunta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questinario_idx` (`id_questionario` ASC) VISIBLE,
  INDEX `fk_tipo_idx` (`id_tipo_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_tipo`
    FOREIGN KEY (`id_tipo_pergunta`)
    REFERENCES `projeto_integrador_ii_a`.`tipo_pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questinario`
    FOREIGN KEY (`id_questionario`)
    REFERENCES `projeto_integrador_ii_a`.`questionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador_ii_a`.`opcao_resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador_ii_a`.`opcao_resposta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `id_pergunta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pergunta_idx` (`id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `projeto_integrador_ii_a`.`pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `projeto_integrador_ii_a`.`tipo_pergunta`
-- -----------------------------------------------------
START TRANSACTION;
USE `projeto_integrador_ii_a`;
INSERT INTO `projeto_integrador_ii_a`.`tipo_pergunta` (`id`, `descricao`) VALUES (1, 'Múltipla escolha');
INSERT INTO `projeto_integrador_ii_a`.`tipo_pergunta` (`id`, `descricao`) VALUES (2, 'Dicotômica');
INSERT INTO `projeto_integrador_ii_a`.`tipo_pergunta` (`id`, `descricao`) VALUES (3, 'Resposta única');
INSERT INTO `projeto_integrador_ii_a`.`tipo_pergunta` (`id`, `descricao`) VALUES (4, 'Discursiva');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projeto_integrador_ii_a`.`questionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `projeto_integrador_ii_a`;
INSERT INTO `projeto_integrador_ii_a`.`questionario` (`id`, `descricao`) VALUES (1, 'Educação para as relações étnico-raciais e cultura afro-brasileira, africana e indígena.');

COMMIT;

